language: ruby
bundler_args: --without guard 
script: "bundle exec rake ci"
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode 
  - rbx-19mode
allowed_failures:
  matrix:
    - 1.8.7
    - jruby-18mode 
    - rbx-18mode
notifications:
  email:
    - mbj@seonic.net
